name: Deploy to Firebase Hosting

on:
  push:
    branches:
      - main  # Adjust to your default branch name

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Install Firebase CLI
      run: npm install -g firebase-tools

    - name: Install dependencies
      working-directory: frontend # Adjust to the folder containing package.json
      run: npm install

    - name: Build project
      working-directory: frontend # Adjust to the folder containing package.json
      run: npm run build

    - name: Deploy to Firebase
      working-directory: frontend # Ensure this points to the correct folder containing firebase.json
      env:
        FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}  # Use Firebase token from GitHub Secrets
      run: firebase deploy --only hosting --project flivoai-d1448
