name: Build and Deploy to S3

on:
  push:
    branches:
      - main  # Trigger the action when code is pushed to the main branch

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js (if using Node.js for build)
        uses: actions/setup-node@v2
        with:
          node-version: '22.12.0'  # Use your required Node.js version

      - name: Install dependencies
        working-directory: ./frontend  # Ensure the path is correct
        run: npm install  # Or use other commands to install dependencies

      - name: Build the project
        working-directory: ./frontend  # Ensure the path is correct
        run: npm run build  # Replace with your build command

      - name: Deploy to S3
        uses: jakejarvis/s3-sync-action@v0.5.0  # GitHub Action to sync with S3
        with:
          bucket: ${{ secrets.myflivointerface }}  # S3 bucket name stored in secrets
          source_dir: './frontend/build'  # Path to your build output
          dest_dir: '/'  # Path in the S3 bucket where files will be uploaded
          region: 'eu-north-1'  # Specify the region
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}  # Use GitHub secrets for AWS access key
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}  # Use GitHub secrets for AWS secret access key
          AWS_REGION: 'eu-north-1'  # Include region in environment variables
