on:
  push:
    branches:
      - main  # Replace with the branch you want to deploy from
jobs:
  build_and_deploy:
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm install  # Adjust if you're using yarn or other tools

      - name: Build project
        run: npm run build  # Adjust based on your project setup

      - name: Deploy to Firebase
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: "${{ secrets.GITHUB_TOKEN }}"
          firebaseServiceAccount: "${{ secrets.FIREBASE_SERVICE_ACCOUNT }}"
          channelId: live
